# site properties and page defaults
title: Patrick Sydow
subtitle: Ph.D. Agricultural and Environmental Plant Science
description: TEST
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: pws5408@psu.edu
  orcid: 0009-0001-4761-5446
  google-scholar: 8VlfH0IAAAAJ
  github: sydowpw

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_researchposts
  - scope:
      type: "researchposts"
    values:
      layout: post
  # markdown files in /_blogposts
  - scope:
      type: "blogposts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  researchposts:
    output: true
  # generate page for each post
  blogposts:
    output: true


# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
